#pragma once

#define RAW_EPSIZE 32

// NOT QMK-specific
#define KEYLIGHT_COUNT 68
#define DYNAMIC_KEYMAP_LAYER_COUNT 2

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

#define RGB_MATRIX_LED_COUNT 89
#define RGB_MATRIX_DRIVER_PIN GP13
#define WS2812_DI_PIN GP13
#define RGBLED_NUM 16

#define I2C_DRIVER I2CD1

#define I2C1_SDA_PIN GP0
#define I2C1_SCL_PIN GP1

#define DEBUG_MATRIX_SCAN_RATE

