ALLOW_WARNINGS = yes
VIA_ENABLE = yes
I2C_DRIVER_REQUIRED = yes
CONSOLE_ENABLE = yes
PRINT_ENABLE = yes

RGBLIGHT_ENABLE = yes
BACKLIGHT_ENABLE = no
WS2812_DRIVER = vendor
RGBLED_NUM = 16

VIRTSER_ENABLE = yes
CDC_ENABLE = yes
EXTRA_USB_INTERFACES = yes

RAW_ENABLE = yes
