#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 2

#define ENABLE_RGB_MATRIX_CYCLE_ALL

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_ALL
#define RGB_MATRIX_LED_COUNT 13
#define RGB_MATRIX_DRIVER_PIN GP13
#define WS2812_DI_PIN GP13
