ALLOW_WARNINGS = yes
VIA_ENABLE = yes
CONSOLE_ENABLE = yes
PRINT_ENABLE = yes

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = yes
BACKLIGHT_ENABLE = no
WS2812_DRIVER = vendor

VIRTSER_ENABLE = yes
CDC_ENABLE = yes
EXTRA_USB_INTERFACES = yes

RAW_ENABLE = yes

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += gc9107_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

QUANTUM_PAINTER_DEBUG = yes
