LITTLEFS_ENABLE = yes
ALLOW_WARNINGS = yes
VIA_ENABLE = yes
CONSOLE_ENABLE = yes
PRINT_ENABLE = yes

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += gc9107_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

SRC += rawhid/module_raw_hid.c

VPATH += keyboards/toffee_studio/module/rawhid

PICO_FLASH_SIZE_BYTES = 16*1024*1024
FLASH_RESERVATION_KB = 1024

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812
WS2812_DRIVER = vendor

VIRTSER_ENABLE = yes

# BACKLIGHT_ENABLE = yes
